server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:myserver_keystore.jks
    key-store-type: PKCS12
    key-store-password: 12345678
    key-password: 12345678
    key-alias: api-server.skshukla.com
    trust-store: classpath:myserver_truststore.jks
    trust-store-password: 12345678
    client-auth: need